export { default as Auburn } from "./Auburn.png";
export { default as Dorado } from "./Dorado.png";
export { default as EastSac } from "./EastSac.png";
export { default as Elk } from "./Elk.png";
export { default as Folsom } from "./Folsom.png";
export { default as Map } from "./Full Screen Map.png";
export { default as Lincoln } from "./Lincoln.png";
export { default as Loomis } from "./Loomis.png";
export { default as Natomis } from "./Natomis.png";
export { default as Rancho } from "./Rancho.png";
export { default as Rocklin } from "./Rocklin.png";
export { default as Roseville } from "./Roseville.png";
export { default as WestSac } from "./WestSac.png";
